jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: xcodebuild -scheme Sticky test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' 

workflows:
  say-hello-workflow:
    jobs:
      - build-and-test
