name: Code Coverage

on:
  push:
    branches: [ "main" ]

jobs:
  post-code-coverage:
    runs-on: macos-latest
    steps:
    - name: Install llvm
      run: brew install llvm
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Run tests to generate code coverage
      run: swift test --enable-code-coverage
    - name: Generate coverage report
      uses: maxep/spm-lcov-action@0.3.1
      with:
        output-file: ./coverage/lcov.info
    - name: Setup .NET Core # Required to execute Generate Coverage HTML Report and Badges
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        dotnet-quality: 'ga'
    - name: Generate Coverage HTML Report and Badges
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.12
      with:
        reports: coverage/lcov.info
        targetdir: coverage
        reporttypes: Html;Badges
    - name: Commit Coverage Files
      run: |
        git push origin --delete main-code-coverage || :
        git checkout -b main-code-coverage
        git add ./coverage
        git commit -m "added coverage report"
        git push -u origin main-code-coverage
