name: Code Coverage

on:
 pull_request:
   branches: [ "main" ]

jobs:
  set-github-status:
    runs-on: macos-latest
    steps:
    - name: Install llvm
      run: brew install llvm
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Run tests to generate code coverage
      run: swift test --enable-code-coverage

    # - name: Generate coverage report
    #   uses: maxep/spm-lcov-action@0.3.1
    #   with:
    #     output-file: ./coverage/lcov.info

    # - name: Post coverage report
    #   uses: romeovs/lcov-reporter-action@v0.2.16
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     lcov-file: ./coverage/lcov.info
    
    # - name: Install NPM package check-code-coverage
    #   run: npm install --global check-code-coverage

    - name: Set code coverage commit status
      run: npx -p check-code-coverage --from $(swift test --show-codecov-path) set-gh-status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
