name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show eligible build destinations for Sticky
      run: xcodebuild -showdestinations -scheme Sticky
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
