name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build-and-test-on-all-platforms:
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Show eligible build destinations for Sticky
      run: xcodebuild -showdestinations -scheme Sticky
    - name: Build and test ( macOS 12.0 Monterey)
      run: xcodebuild test -scheme Sticky -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( mac Catalyst 12.0)
      run: xcodebuild test -scheme Sticky -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( tvOS 15.2)
      run: xcodebuild test -scheme Sticky -destination 'platform=tvOS Simulator,OS=15.2,name=Apple TV 4K (2nd generation)'
    - name: Build and test ( watchOS 8.3)
      run: xcodebuild test -scheme Sticky -destination 'platform=watchOS Simulator,OS=8.3,name=Apple Watch Series 7 - 45mm'
    - name: Build and test ( iPadOS 15.2)
      run: xcodebuild test -scheme Sticky -destination 'platform=iOS Simulator,OS=15.2,name=iPad Pro (12.9-inch) (5th generation)'
    - name: Build and test ( iOS 15.2)
      run: xcodebuild test -scheme Sticky -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro Max'
